### ISSUE TITLE
Send logs to stdout by default

### ISSUE THREAD

**Issue by yuvipanda** [Litipk/Jupyter-PHP#10]
This is what all the other kernels seem to be doing. Could have options that redirect it to a file, but sending it by default also helps in log capture when running on the cloud (see also http://12factor.net/) which is useful for installs like paws.wmflabs.org (where I'm hoping to get this installed!)

**Comment by castarco** [comment]
Hi @yuvipanda , can you confirm that all logs from other kernels are sent to stdout? Is it possible that some logs are being sent to stderr?

**Comment by yuvipanda** [comment]
Good point - I _think_ they're actually going to stderr by default, not
stdout. Not going to a file though!

On Tue, Apr 5, 2016 at 2:36 PM, Andreu Correa Casablanca <
notifications@github.com> wrote:

> Hi @yuvipanda https://github.com/yuvipanda , can you confirm that all
> logs from other kernels are sent to stdout? Is it possible that some logs
> are being sent to stderr?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/Litipk/Jupyter-PHP/issues/10#issuecomment-205994260

## 

Yuvi Panda T
http://yuvi.in/blog

**Comment by castarco** [comment]
Done.

**Comment by yuvipanda** [comment]
Thanks!

On Wed, Apr 6, 2016 at 2:43 PM, Andreu Correa Casablanca <
notifications@github.com> wrote:

> Done.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/Litipk/Jupyter-PHP/issues/10#issuecomment-206584050

## 

Yuvi Panda T
http://yuvi.in/blog
