### ISSUE TITLE
install fails on FreeBSD

### ISSUE THREAD

**Issue by daizus** [Litipk/Jupyter-PHP#12]
Running **php ./jupyter-php-installer.phar install** I get the following error:

> ERROR: Error while trying to download Jupyter-PHP dependencies with Composer.

If I run the **composer install** with the composer.json from the repository it install the dependencies without any problem.
Any idea on how to make this work?
Thank you!

**Comment by meshr-net** [comment]
Run `./jupyter-php-installer.phar install -vvv` to see problems. I had to install zeromq http://www.netcreate.pl/blog/ubuntu-14-04-installing-zeromq/

**Comment by daizus** [comment]
After installing php-zmq it worked.
Thank you!

**Comment by castarco** [comment]
:)
