### ISSUE TITLE
Can't install on win64 php7.0.10

### ISSUE THREAD

**Issue by Zydnar** [Litipk/Jupyter-PHP#13]
When I run: **php jupyter-php-installer.phar install**
it throws: 
_ERROR: Error while trying to download Jupyter-PHP dependencies with Composer._
when I run: **php jupyter-php-installer.phar install -v**
it says:
_The Jupyter-PHP kernel has been successfully installed._
but there is no single trail of php kernel

**Comment by bstoney** [comment]
Should be fixed now, see Litipk/Jupyter-PHP-Installer#14

**Comment by castarco** [comment]
Related with https://github.com/Litipk/Jupyter-PHP-Installer/issues/11 , supposedly fixed.
