### ISSUE TITLE
annoying kernel error msg while typing in hydrogen atom

### ISSUE THREAD

**Issue by Mofiqul** [Litipk/Jupyter-PHP#22]
I have installed Jupyter-PHP everything is fine but i get this annoying error msg each keyword I type in my atom .
OS: Ubuntu 16.04

 `[2017-08-12 14:39:57] ShellMessagesHandler.DEBUG: Received message {"processId":10003,"zmqIds":"dealer23dcb0af-5552-49bd-9cdb-61ff2de89398","hmac":"84f6449c65446f5a1eddfcf08dd9abb0284adffdbeea28dddd520b193327ba64","header":{"username":"evil_reaper","session":"00000000-0000-0000-0000-000000000000","msg_type":"complete_request","msg_id":"complete_b5eea831-619f-49ff-997d-f61c93f9d3b4","date":"2017-08-12T09:09:57.213Z","version":"5.0"},"parentHeader":"{}","metadata":"{}","content":{"code":"$en","text":"$en","line":"$en","cursor_pos":3}} [] [2017-08-12 14:39:57] ShellMessagesHandler.ERROR: Unknown message type {"processId":10003,"header":{"username":"evil_reaper","session":"00000000-0000-0000-0000-000000000000","msg_type":"complete_request","msg_id":"complete_b5eea831-619f-49ff-997d-f61c93f9d3b4","date":"2017-08-12T09:09:57.213Z","version":"5.0"}} []`

**Comment by castarco** [comment]
Hi @Mofiqul , this isn't an error message, but a *debug* message. Where is this message appearing? Can you attach more info? (Something like a screenshot, because I've not worked with Atom's Hydrogen).

Best regards.

**Comment by Mofiqul** [comment]
I don't use atom anymore because I find VS Code more amazing and Jupyter-PHP works out of the box in VS Code.
