### ISSUE TITLE
Why do not syntax highlight the php codes?!

### ISSUE THREAD

**Issue by NabiKAZ** [Litipk/Jupyter-PHP#25]
Why do not syntax highlight the php codes?!
Is not this important?!

**Comment by castarco** [comment]
This is a limitation from the Jupyter's pygment plugin.

You can enable syntax highlighting by writing this as the first line:
```php
//<?php
```

**Comment by NabiKAZ** [comment]
Thanks, But It's bad when we need to print and provide reports and documentations.
