### ISSUE TITLE
Fix `kernel_info_request` timeout

### ISSUE THREAD

**Issue by castarco** [Litipk/Jupyter-PHP#5]
Jupyter Notebook shows a timeout message every time a Jupyter-PHP kernel is started. The timeout is related with the `kerne_info_request` request. In theory, the kernel is responding with a `kernel_info_reply` message, but for some reason this message is not arriving to (or not being accepted by) the kernel.

**EDIT:** This also causes missing syntax highlighting because Jupyter does not receive the needed info to use it in Pygments.

**Comment by yuvipanda** [comment]
This also causes syntax highlighting and what not to not work in the notebook UI.

**Comment by yuvipanda** [comment]
I dug into this a little bit with tcpdump, I see the request but don't see us sending a response:

```
.0i1.0i1.~..{"msg_id": "0b7837ad-4a4b-46bf-a5c4-b1b605a23bd8", "parent_header": {"username": "username", "msg_id": "D4CD48B8ED374A07807A63FB993A2E33", "version": "5.0", "session": "20300F2B62CC4943BEAEB15226B904C8", "msg_type": "kernel_info_request"}, "msg_type": "status", "buffers": [], "metadata": {}, "header": {"date": "2016-04-02T11:54:17", "msg_id": "0b7837ad-4a4b-46bf-a5c4-b1b605a23bd8", "session": "0d44b952-999c-48a9-8789-0a5dcb27d2c8", "username": "kernel", "version": "5.0", "msg_type": "status"}, "content": {"execution_state": "idle"}, "channel": "iopub"}
```

**Comment by yuvipanda** [comment]
This is quite funky, because the logs from jupyter-php say they did send a response.

**Comment by castarco** [comment]
Hi @yuvipanda , yep, it was known that the syntax highlighting depends on the missing reply. I forgot to write that in this issue report, thank you for your comment.

I didn't check the network traffic with tcpdump, good idea. Probably this will help us to find the bug cause :) .

**Comment by smasty** [comment]
Any progress on this? It's a pain to use this without syntax highlighting...

**Comment by castarco** [comment]
@smasty Apparently solved, but syntax highlighting remains buggy.

**Comment by bstoney** [comment]
Syntax highlighting works if you start each code cell with `//<?` It looks like an issue with codemirror where it does not have a reference to the `text/x-php` mime type in meta.js, so will only use `application/x-httpd-php`. Still investigating
